sudo: true
dist: trusty

env:
  - HUGO_THEME=ado
  - HUGO_BASEURL="https://www.arresteddevops.com"

services:
  - docker

before_install:
  - docker run --name "ado-hugo" -P -v $(pwd):/src jojomi/hugo
