sudo: true
dist: trusty

env:
  global:
    - HUGO_THEME=ado
    - HUGO_BASEURL="https://www.arresteddevops.com"

services:
  - docker

script:
  - docker run --name "ado-hugo" -P -v $(pwd):/src jojomi/hugo
