version: "3"
services:
    hugo:
        image: jojomi/hugo:0.61.0
        ports: 
          - 1313:1313
        volumes:
          - ./:/src
          - ./output/:/output
        environment:
          - HUGO_WATCH=true
          - HUGO_THEME=castanet
          - HUGO_BASEURL=http://localhost/
        restart: always