# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
#  command = "bin/netlify.sh"
# publish = "exampleSite/public"
   command = "bin/netlify-production.sh"
   publish = "public/"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "public/"
  command = "bin/netlify.sh"

[context.castanet]
 command = "bin/netlify-castanet.sh"
 publish = "public/"

  [context.production.environment]
     HUGO_VERSION = "0.20.7"

  [context.deploy-preview.environment]
    HUGO_VERSION = "0.20.7"

  [context.branch-deploy.environment]
    HUGO_VERSION = "0.20.7"
